FROM cirapulsarsandtransients/psrchive:latest

RUN apt-get update -y && \
    apt-get install -y python-tk

RUN pip install PyWavelets lmfit

RUN git clone https://github.com/pennucci/PulsePortraiture.git && \
    cd PulsePortraiture &&\
    python setup.py install


